// etnair/client/src/App.vue
<template>
  <div id="app">
    <Header />
    <main>
      <RouterView />
    </main>
    <Footer />
  </div>
</template>

<script setup>
import { RouterView } from 'vue-router'
import Header from '@/components/layout/Header.vue'
import Footer from '@/components/layout/Footer.vue'
</script>

<style scoped>
main {
  min-height: calc(100vh - 120px);
}
</style>

// etnair/client/app/page.tsx
import React from 'react';
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import FirstSection from "@/components/homePage/FirstSection";
import HomesList from "@/components/home/HomesList";

export default function HomePage() {
  return (
      <div className="min-h-screen flex flex-col bg-gray-50">
        <Header />

        <main className="grow">
            <FirstSection />
            <HomesList />
        </main>

        <Footer />
      </div>
  );
}
