// etnair/client/components/home/HomeCard.tsx
import React from 'react';
import { Home, getPropertyTypeLabel, getFirstImageKey } from '@/types/home';
import { getProxiedImageKey } from '@/utils/imageProxy';

interface HomeCardProps {
    home: Home;
}

export default function HomeCard({ home }: HomeCardProps) {
    const firstImageKey = getFirstImageKey(home);
    const proxiedImage = getProxiedImageKey(firstImageKey);
    const propertyLabel = getPropertyTypeLabel(home.propertytype);

    return (
        <div className="bg-white rounded-lg overflow-hidden shadow-sm hover:shadow-md transition">
            <div className="w-full h-48 bg-gray-200">
                {proxiedImage ? (
                    <img
                        src={proxiedImage}
                        alt={home.namehome}
                        className="w-full h-full object-cover"
                    />
                ) : (
                    <div className="w-full h-full flex items-center justify-center text-gray-400">
                        Pas d'image
                    </div>
                )}
            </div>
            <div className="p-4">
                <div className="flex items-center justify-between mb-2">
                    <span className="text-sm text-gray-500">{propertyLabel}</span>
                    <span className="text-sm text-gray-500">{home.city}</span>
                </div>
                <h3 className="text-lg font-semibold text-[#153563] mb-2">
                    {home.namehome}
                </h3>
                <p className="text-gray-600">
                    À partir de <span className="font-semibold">{home.price}€</span>/nuit
                </p>
            </div>
        </div>
    );
}

// etnair/client/src/components/home/HomeCard.vue
<template>
  <div class="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-xl transition cursor-pointer">
    <div class="h-48 bg-gray-300 flex items-center justify-center">
      <img
          v-if="home.image"
          :src="home.image"
          :alt="home.title"
          class="w-full h-full object-cover"
      />
      <span v-else class="text-gray-500">Image</span>
    </div>

    <div class="p-4">
      <h3 class="font-semibold text-lg mb-2">{{ home.title }}</h3>
      <p class="text-gray-600 text-sm mb-3">
        {{ 'À partir de ...' }}
      </p>
      <div class="flex justify-between items-center">
        <span class="text-primary font-bold">
          {{ formatPrice(home.price) }}
        </span>
      </div>
    </div>
  </div>
</template>

<script setup>
import { defineProps } from 'vue'

defineProps({
  home: {
    type: Object,
    required: true
  }
})

const formatPrice = (price) => {
  if (!price) return 'Prix sur demande'
  return new Intl.NumberFormat('fr-FR', {
    style: 'currency',
    currency: 'EUR'
  }).format(price)
}
</script>
