// etnair/client/components/home/HomesList.tsx
"use client";

import React from 'react';
import HomeCard from '@/components/home/HomeCard';
import { useHomes } from '@/hooks/useHomes';

export default function HomesList() {
    const { homes, loading, error } = useHomes();

    if (loading) {
        return (
            <div className="py-12">
                <h2 className="text-3xl font-bold text-[#153563] text-center mb-8">
                    Nouvelles annonces
                </h2>
                <div className="text-center text-gray-600">Chargement...</div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="py-12">
                <h2 className="text-3xl font-bold text-[#153563] text-center mb-8">
                    Nouvelles annonces
                </h2>
                <div className="text-center text-red-600">{error}</div>
            </div>
        );
    }

    if (!Array.isArray(homes)) {
        console.error('homes n\'est pas un tableau:', homes);
        return (
            <div className="py-12">
                <h2 className="text-3xl font-bold text-[#153563] text-center mb-8">
                    Nouvelles annonces
                </h2>
                <div className="text-center text-red-600">Format de données invalide</div>
            </div>
        );
    }

    // Prendre les 4 dernières annonces
    const latestHomes = homes.slice(-4).reverse();

    if (latestHomes.length === 0) {
        return (
            <div className="py-12">
                <h2 className="text-3xl font-bold text-[#153563] text-center mb-8">
                    Nouvelles annonces
                </h2>
                <div className="text-center text-gray-600">Aucune annonce disponible</div>
            </div>
        );
    }

    return (
        <div className="py-12 bg-gray-50">
            <div className="container mx-auto px-4">
                <h2 className="text-3xl font-bold text-[#153563] text-center mb-8">
                    Nouvelles annonces
                </h2>
                <ul className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                    {latestHomes.map((home) => (
                        <li key={home.idhome}>
                            <HomeCard home={home} />
                        </li>
                    ))}
                </ul>
            </div>
        </div>
    );
}

// etnair/client/src/components/home/HomesList.vue
<template>
  <section class="py-16 bg-gray-50">
    <div class="container mx-auto px-4">
      <h2 class="text-3xl font-bold text-center mb-12">Nouvelles annonces</h2>

      <div v-if="loading" class="text-center">
        <p class="text-gray-600">Chargement des annonces...</p>
      </div>

      <div v-else-if="error" class="text-center text-red-600">
        <p>{{ error }}</p>
      </div>

      <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <HomeCard
            v-for="home in homes"
            :key="home.id"
            :home="home"
        />
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import HomeCard from './HomeCard.vue'
import api from '@/services/api'

const homes = ref([])
const loading = ref(true)
const error = ref(null)

onMounted(async () => {
  try {
    const response = await api.getHomes()
    homes.value = response.data
  } catch (err) {
    error.value = 'Impossible de charger les annonces'
    console.error(err)
  } finally {
    loading.value = false
  }
})
</script>
